# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog, QMainWindow

sys.path.append("..")


class Ui_doorWindow(object):
    def __init__(self):
        self.code_path = os.path.dirname(os.path.abspath(__file__))  # 获取代码路径
        self.project_path = os.path.dirname(self.code_path)  # 获取识别项目路径
        self.source_path = os.path.join(
            self.project_path, "resources")  # 获取依赖数据路径
        self.photo_path = os.path.join(
            self.source_path, "FaceImage")  # 获取人脸文件夹路径

        self.runflag = False  # 循环起始控制变量

    def setupUi(self, doorWindow):
        doorWindow.setObjectName("doorWindow")
        doorWindow.resize(1081, 812)
        self.centralwidget = QtWidgets.QWidget(doorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 20, 561, 731))
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.label_1 = QtWidgets.QLabel(self.frame1)
        self.label_1.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.label_1.setObjectName("label_1")
        self.NormalFace = QtWidgets.QLabel(self.frame1)
        self.NormalFace.setGeometry(QtCore.QRect(20, 60, 521, 551))
        self.NormalFace.setFrameShape(QtWidgets.QFrame.Box)
        self.NormalFace.setText("")
        self.NormalFace.setObjectName("NormalFace")
        self.stopButton = QtWidgets.QPushButton(self.frame1)
        self.stopButton.setGeometry(QtCore.QRect(200, 630, 131, 61))
        self.stopButton.setObjectName("stopButton")
        self.startButton = QtWidgets.QPushButton(self.frame1)
        self.startButton.setGeometry(QtCore.QRect(30, 630, 131, 61))
        self.startButton.setObjectName("startButton")
        self.registButton = QtWidgets.QPushButton(self.frame1)
        self.registButton.setGeometry(QtCore.QRect(380, 630, 131, 61))
        self.registButton.setObjectName("registButton")
        self.NormalFace.raise_()
        self.label_1.raise_()
        self.stopButton.raise_()
        self.startButton.raise_()
        self.registButton.raise_()
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(580, 30, 451, 731))
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.label_2 = QtWidgets.QLabel(self.frame2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame2)
        self.label_3.setGeometry(QtCore.QRect(20, 510, 131, 16))
        self.label_3.setObjectName("label_3")
        self.Button_OpenPhoto = QtWidgets.QPushButton(self.frame2)
        self.Button_OpenPhoto.setGeometry(QtCore.QRect(160, 680, 131, 41))
        self.Button_OpenPhoto.setObjectName("Button_OpenPhoto")
        self.ErrorText = QtWidgets.QPlainTextEdit(self.frame2)
        self.ErrorText.setGeometry(QtCore.QRect(10, 530, 421, 141))
        self.ErrorText.setObjectName("ErrorText")
        self.ErrorFace = QtWidgets.QLabel(self.frame2)
        self.ErrorFace.setGeometry(QtCore.QRect(10, 50, 421, 441))
        self.ErrorFace.setFrameShape(QtWidgets.QFrame.Box)
        self.ErrorFace.setText("")
        self.ErrorFace.setIndent(6)
        self.ErrorFace.setObjectName("ErrorFace")
        doorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(doorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName("menubar")
        doorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(doorWindow)
        self.statusbar.setObjectName("statusbar")
        doorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(doorWindow)
        QtCore.QMetaObject.connectSlotsByName(doorWindow)

        # 设置按钮响应
        self.startButton.clicked.connect(self.start)
        self.stopButton.clicked.connect(self.stop)

    def retranslateUi(self, doorWindow):
        _translate = QtCore.QCoreApplication.translate
        doorWindow.setWindowTitle(_translate("doorWindow", "智能门禁"))
        self.label_1.setText(_translate("doorWindow", "检测显示窗口"))
        self.stopButton.setText(_translate("doorWindow", "停止检测"))
        self.startButton.setText(_translate("doorWindow", "开始检测"))
        self.registButton.setText(_translate("doorWindow", "主人人脸记录"))
        self.label_2.setText(_translate("doorWindow", "异常人脸显示窗口"))
        self.label_3.setText(_translate("doorWindow", "异常人脸记录："))
        self.Button_OpenPhoto.setText(_translate("doorWindow", "查看异常人脸图片"))

    def start(self):
        self.runflag = True  # 开始循环
        while self.runflag:
            if not os.listdir(self.photo_path) == 0:
                imagePaths = [os.path.join(self.photo_path, f)
                              for f in os.listdir(self.photo_path)]  # 列表生成式产生图像路径列表
                for imagePath in imagePaths:
                    pass

    def stop(self):
        self.runflag = False
        # 发送树莓派终止信号


class doorWindow(QMainWindow):
    def __init__(self):
        QDialog.__init__(self)
        self.child = Ui_doorWindow()
        self.child.setupUi(self)
