# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitchenWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import cv2
from PyQt5.QtGui import QImage, QPixmap

sys.path.append("..")
import time

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QObject, QThread, QTimer, pyqtSignal
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow, QMessageBox

from Detection.Fire_Detection.Fire_Rec import *
from FileAndSql.remoteSSH import SSH
from FileAndSql.fileAndLog import fileAndLog

import resource_qrc_rc


class Ui_kitchenWindow(object):

    def setupUi(self, kitchenWindow):
        kitchenWindow.setObjectName("kitchenWindow")
        kitchenWindow.resize(1080, 800)
        kitchenWindow.setStyleSheet("#kitchenWindow{border-image: url(:/Resources/background.png);}\n""")
        self.centralwidget = QtWidgets.QWidget(kitchenWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 1, 13, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 12, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 0, 1, 1)
        self.GasLable = QtWidgets.QLabel(self.centralwidget)
        self.GasLable.setObjectName("GasLable")
        self.gridLayout.addWidget(self.GasLable, 8, 10, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 14, 1, 1)
        self.Button_OpenPhoto = QtWidgets.QPushButton(self.centralwidget)
        self.Button_OpenPhoto.setMinimumSize(QtCore.QSize(100, 60))
        self.Button_OpenPhoto.setObjectName("Button_OpenPhoto")
        self.gridLayout.addWidget(self.Button_OpenPhoto, 17, 5, 3, 4)
        self.FireLable = QtWidgets.QLabel(self.centralwidget)
        self.FireLable.setObjectName("FireLable")
        self.gridLayout.addWidget(self.FireLable, 10, 10, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 7, 0, 1, 1)
        self.SmogLable = QtWidgets.QLabel(self.centralwidget)
        self.SmogLable.setObjectName("SmogLable")
        self.gridLayout.addWidget(self.SmogLable, 6, 10, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 18, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(True)
        self.startButton.setMinimumSize(QtCore.QSize(100, 60))
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 17, 14, 3, 2)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 11, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 17, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 19, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 11, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 14, 0, 1, 1)
        self.NormalImageLable = QtWidgets.QLabel(self.centralwidget)
        self.NormalImageLable.setFrameShape(QtWidgets.QFrame.Box)
        self.NormalImageLable.setText("")
        self.NormalImageLable.setObjectName("NormalImageLable")
        self.gridLayout.addWidget(self.NormalImageLable, 2, 12, 15, 8)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 17, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 8, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 19, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 16, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 10, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 15, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 13, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 0, 18, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 7, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 0, 10, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem21, 9, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem22, 15, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem23, 4, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem24, 0, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem25, 0, 15, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem26, 0, 20, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem27, 0, 5, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem29, 6, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem30, 1, 0, 1, 1)
        self.Gas = QtWidgets.QLabel(self.centralwidget)
        self.Gas.setObjectName("Gas")
        self.gridLayout.addWidget(self.Gas, 8, 11, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 3, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem32, 0, 0, 1, 1)
        self.Smog = QtWidgets.QLabel(self.centralwidget)
        self.Smog.setObjectName("Smog")
        self.gridLayout.addWidget(self.Smog, 6, 11, 1, 1)
        self.TemperatureLable = QtWidgets.QLabel(self.centralwidget)
        self.TemperatureLable.setObjectName("TemperatureLable")
        self.gridLayout.addWidget(self.TemperatureLable, 2, 10, 1, 1)
        self.ErrorImageLable = QtWidgets.QLabel(self.centralwidget)
        self.ErrorImageLable.setFrameShape(QtWidgets.QFrame.Box)
        self.ErrorImageLable.setText("")
        self.ErrorImageLable.setObjectName("ErrorImageLable")
        self.gridLayout.addWidget(self.ErrorImageLable, 4, 1, 11, 9)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 9, 1, 1)
        self.Fire = QtWidgets.QLabel(self.centralwidget)
        self.Fire.setObjectName("Fire")
        self.gridLayout.addWidget(self.Fire, 10, 11, 1, 1)
        self.Temperature = QtWidgets.QLabel(self.centralwidget)
        self.Temperature.setObjectName("Temperature")
        self.gridLayout.addWidget(self.Temperature, 2, 11, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem34, 0, 8, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem35, 0, 13, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem36, 0, 6, 1, 1)
        self.Humidity = QtWidgets.QLabel(self.centralwidget)
        self.Humidity.setObjectName("Humidity")
        self.gridLayout.addWidget(self.Humidity, 4, 11, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem37, 5, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(100, 60))
        self.stopButton.setObjectName("stopButton")
        self.gridLayout.addWidget(self.stopButton, 17, 17, 3, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem38, 3, 0, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem39, 0, 16, 1, 1)
        self.HumidityLable = QtWidgets.QLabel(self.centralwidget)
        self.HumidityLable.setObjectName("HumidityLable")
        self.gridLayout.addWidget(self.HumidityLable, 4, 10, 1, 1)
        self.ErrorText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ErrorText.setObjectName("ErrorText")
        self.gridLayout.addWidget(self.ErrorText, 16, 1, 1, 9)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        kitchenWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kitchenWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        kitchenWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kitchenWindow)
        self.statusbar.setObjectName("statusbar")
        kitchenWindow.setStatusBar(self.statusbar)

        self.retranslateUi(kitchenWindow)
        QtCore.QMetaObject.connectSlotsByName(kitchenWindow)

        # 设置按钮响应
        self.startButton.clicked.connect(self.start)
        self.stopButton.clicked.connect(self.stop)
        self.Button_OpenPhoto.clicked.connect(self.open)

    def retranslateUi(self, kitchenWindow):
        _translate = QtCore.QCoreApplication.translate
        kitchenWindow.setWindowTitle(_translate("kitchenWindow", "智能厨房"))
        self.label1.setText(_translate("kitchenWindow", "实时画面显示窗口"))
        self.GasLable.setText(_translate("kitchenWindow", "  燃气："))
        self.Button_OpenPhoto.setText(_translate("kitchenWindow", "查看异常记录"))
        self.FireLable.setText(_translate("kitchenWindow", "  火焰："))
        self.SmogLable.setText(_translate("kitchenWindow", "  烟雾："))
        self.startButton.setText(_translate("kitchenWindow", "开始检测"))
        self.label2.setText(_translate("kitchenWindow", "异常图片显示窗口"))
        self.label3.setText(_translate("kitchenWindow", "异常人脸记录："))
        self.Gas.setText(_translate("kitchenWindow", "NULL"))
        self.Smog.setText(_translate("kitchenWindow", "NULL"))
        self.TemperatureLable.setText(_translate("kitchenWindow", "  温度："))
        self.Fire.setText(_translate("kitchenWindow", "NULL"))
        self.Temperature.setText(_translate("kitchenWindow", "NULL"))
        self.Humidity.setText(_translate("kitchenWindow", "NULL"))
        self.stopButton.setText(_translate("kitchenWindow", "停止检测"))
        self.HumidityLable.setText(_translate("kitchenWindow", "  湿度："))


class MyThread(QObject):
    startsig = pyqtSignal(int)  # 开始识别信号
    endsig = pyqtSignal(int)  # 识别结束 界面更新信号

    def __init__(self):
        super(MyThread, self).__init__()
        self.firerec = Fire_Recognition()

    def work(self, f):
        if f == 1:
            global img2
            flag, img2 = self.firerec.fire_reconfnition(img1)
            self.endsig.emit(flag)  # 采用信号可使线程自动结束


class MainWindow(QtWidgets.QMainWindow, Ui_kitchenWindow):  # 继承qtdesiner的MinWindow 确保window为qtwidgets 不然massagebox无法启用

    def __init__(self, *args, **kwargs):
        QtWidgets.QMainWindow.__init__(self, *args, **kwargs)

        self.code_path = os.path.dirname(os.path.abspath(__file__))  # 获取代码路径
        self.project_path = os.path.dirname(self.code_path)  # 获取识别项目路径
        self.photo_path = r'\\192.168.137.69\pi\share\otherImage'
        self.source_path = os.path.join(
            self.project_path, "Resources")  # 获取依赖数据路径
        self.errors_path = os.path.join(
            self.source_path, "Errors")  # 获取依赖数据路径
        self.imagePath = os.path.join(self.photo_path, r'1.jpg')

        self.thread = QThread()
        self.myThread = MyThread()
        self.myThread.moveToThread(self.thread)
        self.myThread.startsig.connect(self.myThread.work)
        self.myThread.endsig.connect(self.update)
        self.thread.start()

        self.ssh = SSH()
        self.log = fileAndLog()
        self.timer = QTimer()
        self.timer.timeout.connect(self.run)

    def run(self):
        if len(os.listdir(self.photo_path)) == 1:
            global img1
            img1 = cv2.imread(self.imagePath)
            self.NormalImageLable.setPixmap(
                QPixmap(self.imagePath).scaled(493, 572))
            QApplication.processEvents()
            self.myThread.startsig.emit(1)
            os.remove(self.imagePath)

    def start(self):

        self.startButton.setEnabled(False)  # 禁止重复开始
        self.stopButton.setEnabled(True)
        self.ssh.startOther()
        time.sleep(2)
        self.timer.start(100)

    def update(self, flag):
        if flag:
            height, width, bytesPerComponent = img2.shape
            bytesPerLine = bytesPerComponent * width
            show = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)  # 视频色彩转换回RGB，这样才是现实的颜色
            showImage = QImage(show.data, width, height, bytesPerLine,
                               QImage.Format_RGB888)  # 把读取到的视频数据变成QImage形式
            self.ErrorImageLable.setPixmap(
                QPixmap.fromImage(showImage).scaled(466, 298))
            QApplication.processEvents()
            logtext = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
            logtext += " 图像检测发现有火焰"
            # self.log.save(img1, 2)  # 保存图片，写入日志
            self.ErrorText.appendPlainText(logtext)  # 插入窗口日志

    def stop(self):
        replay = QMessageBox.question(self, "", "确认停止嘛", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if replay == QMessageBox.Yes:
            self.ssh.stopOther()  # 树莓派结束拍摄
            self.timer.stop()  # 结束识别
            self.NormalImageLable.clear()
            self.ErrorImageLable.clear()
            self.ssh.clear()  # 清空文件夹
            self.startButton.setEnabled(True)
            self.stopButton.setEnabled(False)

    def closeEvent(self, event):
        self.ssh.stopOther()
        self.ssh.clear()  # 清空文件夹
        event.accept()

    def open(self):
        os.system("explorer.exe %s" % self.errors_path)


class kitchenWindow(QMainWindow):
    def __init__(self):
        QDialog.__init__(self)
        super().__init__()
        self.child = MainWindow()
        self.child.setupUi(self)
